{% set name = "dmd" %}
{% set version = "2.079.0" %}
{% set sha256 = "f3f4c8f6c2e5cdd0ac335e56613663bee075a1e797ffbb55035d6c767d7bc585" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}.{{ version }}.zip
  url: http://downloads.dlang.org/releases/2018/{{ name }}.{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [not linux64]
  
test:
  commands:    
    - dmd 2>&1 | head -n 1 | grep -q '^DMD64 D Compiler v2.079'; echo $?

about:
  home: https://github.com/dlang/dmd
  license: Boost Software, Version 1.0
  summary: 'DMD is the reference compiler for the D programming language.'

extra:
  recipe-maintainers:
    - pirovc
    - abhi18av
