{% set version = "2.109.1" %}

package:
  name: dmd
  version: {{ version }}

source:
  - url: https://github.com/dlang/dmd/archive/v{{ version }}.tar.gz
    sha256: 8c2ce18945e3807a1568f6ec6ce0a8f2b88efa472ce0397ea1305fc2a1b8a587
    folder: dmd
  - url: https://github.com/dlang/phobos/archive/v{{ version }}.tar.gz
    sha256: 28974debe14d18eb58591db0dad3ddd4139e8f34783c3648c86619b67d7ba6f2
    folder: phobos

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - ldc
    - make
  
test:
  commands:
    - dmd --version 2>&1 | grep -q \"D Compiler\"

about:
  home: https://github.com/dlang/dmd
  license: BSL-1.0
  license_file: dmd/LICENSE.txt
  summary: 'DMD is the reference compiler for the D programming language.'

extra:
  recipe-maintainers:
    - danielnachun
    - pirovc
