travis:
  secure:
    BINSTAR_TOKEN: f0k3SlqmiX4njbWJTkjmYhRBzfOsB7ngyg1P+ThmtujAQIhI4cGP5dDRwGqsxB1vri6Prk7+f7KZJd733B6YgnlFDQxSjC024lnClrkCTiu1YaEM1TI63duAlK2/n0L6uu8qF4QSHPxcbCutMzb/6sjkoyuf3GznJZaWMH0PhiOw+faJ/XkirAc0PZwKCDQ+CZt8enI5/zThUAM9KcqC7YPRw3WQFkwf4aGL3mfH3xb7YR1QmZb+wYxbcdQwUFehrmWgiJpjC7OprktzcCcBNWzX53RwMct3PKnxDM1HO9Q1ECBg9bTLwC2WGzr855zGz/KSoolUvUVrnjqEFgsEe7M0AeoXFYAtWMmEhskADcxcJsr3SHcRytzGWhW/2V49cfvUpsgrCBTDtLe9SEpqFt86FaJMzHfPYi8lQHa/47kaZ7fuikKM0R3y+nq7ihLGmuTivtb1ZmqAQ9WvifRUrSzrCylzi3MruoluazD/DOmkCMsFMYfmiK2heH0gBc7vG/b8Y4Xtj9Gcc8+dKRlQsSxjnDOaZ4QH7sxAeruV4y825oBjw2esV6NGKIpLy/duGiMExgkwtvcjmXjIcHfRtpfE3JW8NjC1tpuprNytKMe9Y+kAgD9B4yixM27OIiEspJ54JeMUTT1QzcRHW5n3H7NSYHbkQXaCAkxUq1dNj4o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
